In [1]:
# Importing necessary libraries

import os 
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf

In [2]:
df = pd.read_csv(r'C:\Users\sayanezio\Desktop\Kaggle Bank Churn\archive_2\Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

# Data Preprocessing

In [14]:
df = df.drop(['RowNumber','CustomerId','Surname'], axis = 'columns')

In [23]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [18]:
# Defining the dependent and independent variable

In [24]:
x = df.drop(['Exited'], axis = 'columns').values

In [26]:
y = df['Exited'].values

In [25]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [27]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

# Converting the categorical features

In [17]:
le = LabelEncoder()

In [30]:
x[:,2] = le.fit_transform(x[:,2])

In [31]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [33]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')

In [34]:
x = ct.fit_transform(x)

In [38]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [46]:
x[9]

array([1.0, 0.0, 0.0, 684, 1, 27, 2, 134603.88, 1, 1, 1, 71725.73],
      dtype=object)

# Spliting the data into train and test

In [39]:
from sklearn.model_selection import train_test_split

In [47]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state=0)

# Feature Scaling 

In [48]:
sc = StandardScaler()

In [49]:
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [53]:
x_train.shape

(8000, 12)

In [51]:
x_test

array([[-0.95692675,  1.62776996, -0.57427105, ...,  0.66011376,
         0.97628121,  1.62185911],
       [ 1.04501206, -0.61433742, -0.57427105, ...,  0.66011376,
        -1.02429504,  0.504204  ],
       [-0.95692675, -0.61433742,  1.74133801, ...,  0.66011376,
         0.97628121, -0.41865644],
       ...,
       [-0.95692675, -0.61433742,  1.74133801, ...,  0.66011376,
        -1.02429504,  0.72775202],
       [-0.95692675,  1.62776996, -0.57427105, ...,  0.66011376,
         0.97628121, -1.54162886],
       [-0.95692675,  1.62776996, -0.57427105, ...,  0.66011376,
        -1.02429504,  1.62356528]])

# Building ANN Model

In [54]:
# Defining the Layers of ANN model

ann = tf.keras.models.Sequential()

# First Hidden Layer

ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

# Second Hidden layer

ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

# Third Hidden layes

ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

# Output Layer

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Compiling the ANN model

In [55]:
ann.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

# Training The ANN model

In [56]:
ann.fit(x_train, y_train, batch_size=32, epochs=200)

Epoch 1/200


250/250 [==============================] - 2s 2ms/step - loss: 0.5075 - accuracy: 0.7804
Epoch 2/200
250/250 [==============================] - 1s 3ms/step - loss: 0.4404 - accuracy: 0.8074
Epoch 3/200
250/250 [==============================] - 1s 2ms/step - loss: 0.4153 - accuracy: 0.8248
Epoch 4/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3970 - accuracy: 0.8332
Epoch 5/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3770 - accuracy: 0.8450
Epoch 6/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3597 - accuracy: 0.8536
Epoch 7/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3496 - accuracy: 0.8581
Epoch 8/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3445 - accuracy: 0.8605
Epoch 9/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3419 - accuracy: 0.8591
Epoch 10/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3394 - accu

250/250 [==============================] - 1s 3ms/step - loss: 0.3175 - accuracy: 0.8676
Epoch 77/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3172 - accuracy: 0.8696
Epoch 78/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3178 - accuracy: 0.8670
Epoch 79/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3171 - accuracy: 0.8694
Epoch 80/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3171 - accuracy: 0.8692
Epoch 81/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3172 - accuracy: 0.8712
Epoch 82/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3167 - accuracy: 0.8715
Epoch 83/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3168 - accuracy: 0.8706
Epoch 84/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3164 - accuracy: 0.8702
Epoch 85/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3160 - accuracy: 

250/250 [==============================] - 1s 2ms/step - loss: 0.3082 - accuracy: 0.8723
Epoch 156/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3090 - accuracy: 0.8729
Epoch 157/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3080 - accuracy: 0.8736
Epoch 158/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3091 - accuracy: 0.8721
Epoch 159/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3089 - accuracy: 0.8721
Epoch 160/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3082 - accuracy: 0.8720
Epoch 161/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3084 - accuracy: 0.8729
Epoch 162/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3086 - accuracy: 0.8724
Epoch 163/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3078 - accuracy: 0.8752
Epoch 164/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3079 - a

# Prediction and Result

In [57]:
ann.predict(x_test)

63/63 [==============================] - 0s 1ms/step


array([[0.07273766],
       [0.2083141 ],
       [0.09442868],
       ...,
       [0.13619387],
       [0.17356896],
       [0.20489314]], dtype=float32)

In [58]:
y_pred = ann.predict(x_test)

63/63 [==============================] - 0s 2ms/step


In [59]:
y_pred = (y_pred > 0.5)

In [60]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [64]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [62]:
print(accuracy_score(y_test,y_pred))

0.853


In [63]:
print(confusion_matrix(y_test,y_pred))

[[1522   73]
 [ 221  184]]


In [65]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.87      0.95      0.91      1595
           1       0.72      0.45      0.56       405

    accuracy                           0.85      2000
   macro avg       0.79      0.70      0.73      2000
weighted avg       0.84      0.85      0.84      2000

